version: "3.8"
services:
  mongo:
    image: mongo:7.0.14
    container_name: mongo
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet --host localhost
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    ports:
      - "${SPRING_DATA_SERVER_PORT}:8080"
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}
      SERVER_PORT: ${SPRING_DATA_SERVER_PORT}
    volumes:
      - ./src:/app/src
      - ./src/main/java:/app/src/main/java
      - ./src/main/resources:/app/src/main/resources
      - ./build/classes:/app/build/classes

volumes:
  mongo_data:
