version: "3.8"
services:
  mongo:
    image: mongo:7.0.14
    container_name: mongo
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    ports:
      - "${SPRING_SERVER_PORT}:8080"
    depends_on:
      - mongo
    environment:
      MONGO_URI: ${SPRING_MONGO_URI}
      SERVER_PORT: ${SPRING_SERVER_PORT}

volumes:
  mongo_data:
